name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
